### ISSUE TITLE
Gas limit when using multicall

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-eth-py#254]
**Describe the bug**
`eth_call` has a gas limit
 
**To Reproduce**
Do `eth_call` consuming the maximum gas allowed by the node. Library raises an exception. Example trace from the `transaction-service`:
```
2022-05-16 10:23:21,794 [WARNING] [MainProcess] https://safe-transaction.mainnet.gnosis.io/api/v1/safes/{address}/collectibles/ - Exception: NodeConnectionException - Data received {}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gnosis/eth/multicall.py", line 227, in _try_aggregate
    result = self.contract.functions.tryAggregate(
  File "/usr/local/lib/python3.10/site-packages/web3/contract.py", line 957, in call
    return call_contract_function(
  File "/usr/local/lib/python3.10/site-packages/web3/contract.py", line 1501, in call_contract_function
    return_data = web3.eth.call(
  File "/usr/local/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/local/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/usr/local/lib/python3.10/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32015, 'message': 'VM execution error.', 'data': 'Out of gas'}
```

**Expected behavior**
Reverts to use `batch call`

**Comment by 007vasy** [comment]
@Uxio0 has a look at [github.com/banteg/multicall.py](github.com/banteg/multicall.py) if you want to fix it

**Comment by Uxio0** [comment]
Sorry @007vasy , what exactly do we have to take a look at?

**Comment by 007vasy** [comment]
you can set the maximum gas and also multicall.py does a backtrack and tries to do the multicall with less amount of calls

**Comment by Uxio0** [comment]
Yeah, I mean, our biggest problem here is how to do it without impacting performance. Fallbacking to use less amount of calls after a failure is something we want to prevent

**Comment by 007vasy** [comment]
my best guess is that some contracts are faulty and the functions are tagged incorrectly (a view function which is not tagged as view) therefore the node think it needs gas, but it does not (but that's just a guess)

**Comment by Uxio0** [comment]
Well, it's not just gas. For example, Erigon has an `evm` timeout of 5 seconds and gas does not matter too much. Gladly, in the new Erigon versions it can be configured
